### PR TITLE
Indexer syslog tcp

### PR DESCRIPTION
**Pull request by itsecureadmin**
Adds indexer support for syslog over TCP.  The primary driver for this is to support highly available logstash instances behind a load balancer.

- does not support SSL

### CODE REVIEW

**Comment by itsecureadmin** [comment]
It looks like we need a syslog server listening on 514/TCP to successfully test.

**Comment by jakub-bochenski** [comment]
@itsecureadmin thanks for the PR 
If you need a syslog server for the tests I suggest you setup one from Java, e.g. https://github.com/kwart/simple-syslog-server

**Comment by itsecureadmin** [comment]
@jakub-bochenski thanks for the feedback.

I spent some time trying to get the syslog server running via java and realized instead that most of these tests do not spin up an actual server but use mock (new to me) to fake it.  Do we need to spin up a syslog server to validate this test or can we rely solely on the mock tests?  The Syslog indexer that uses UDP sends an actual syslog message that is, apparently, received by the local syslog server running on the test machine.

**Comment by jakub-bochenski** [comment]
@itsecureadmin 
> Do we need to spin up a syslog server to validate this test or can we rely solely on the mock tests? 

The more coverage the better, that said I think currently the different backends only have mock tests

> The Syslog indexer that uses UDP sends an actual syslog message that is, apparently, received by 

the local syslog server running on the test machine.
If you mean the [SyslogDaoTest](https://github.com/jenkinsci/logstash-plugin/blob/master/src/test/java/jenkins/plugins/logstash/persistence/SyslogDaoTest.java
)  it's using a ` @Mock UdpSyslogMessageSender`

**Comment by jakub-bochenski** [comment]
@itsecureadmin 
Checked your code and it seems you are also using a ` @Mock TcpSyslogMessageSender mockTcpSyslogMessageSender;`, but as seen in the CI console it's still invoking the actual method. 

I just volunteered to maintain this project recently so I'm not too familiar with the plumbing here.. Could you check this mock issue locally?

**Comment by itsecureadmin** [comment]
@jakub-bochenski 
I can get the tests to pass if I spin up a syslog server listening on 514/TCP locally and get a failure without the syslog server running.  I also note that I don't get a failure on the Syslog UDP test with or without the syslog server running, which leads me to believe that there is something wrong with my test(s), although when I setup a syslog server listening on both 514/TCP and 514/UDP I get real messages logged from both, ie:

```
2017-05-26T14:59:00.275Z localhost jenkins: @cee: { 'junit': 'SyslogDaoTest' }
2017-05-26T14:59:00.486Z localhost jenkins: @cee: { 'junit': 'SyslogTCPDaoTest' }#015
```

I will spend a bit more time on this today to try and figure it out.  I would like to spin up a syslog server as part of the tests but I could use some guidance on that end.  Do you have a recommended way of starting the executable jar that is provided by the project you referenced above --
 (https://github.com/kwart/simple-syslog-server?

**Comment by itsecureadmin** [comment]
@jakub-bochenski 
The SyslogUDP test is finishing successfully only because UDP does not require a response and does not perform error checking or connection setup.  I ran a packet capture and that is what I'm seeing.

**Comment by jakub-bochenski** [comment]
@itsecureadmin I only now noticed that there are two instances of `*SyslogMessageSender` in the tests:
```
 UdpSyslogMessageSender testSyslogSend = new UdpSyslogMessageSender();
@Mock UdpSyslogMessageSender mockUdpSyslogMessageSender;
```
and the `syslogSend()` test method doesn't even touch the class under test... weird

I'd be in favor of removing this test case altogether, as I don't see any point in re-testing the Cloudbees SyslogMessageSender there.

**Comment by jakub-bochenski** [comment]
@sysadmin4j you authored 9618eb2d4f3bcbd40250f5cc7db221162704ddbb -- do you remember what is the purpose of `syslogSend()` in the SyslogDaoTest?

**Comment by jakub-bochenski** [comment]
@itsecureadmin test issues not withstanding I'd rather add this functionality into the old syslog backend -- otherwise I fear we might get combination explosion when more options appear.

The [elasticsearch backend](https://github.com/jenkinsci/logstash-plugin/blob/master/src/main/java/jenkins/plugins/logstash/persistence/ElasticSearchDao.java#L79) already requires a scheme in host field to support HTTP or HTTPS.

As a quick solution I'd try the same in syslog, supporting either "udp:" or "tcp:" prefix (defaulting to UDP).
A proper solution would be to add a separate "Protocol" field to config.
WDYT?

**Comment by sysadmin4j** [comment]
@jakub-bochenski, the test only send a syslog message to localhost via UDP port 514.
There is no validation that the message has been actually well received on the server side.

At the time I built this test, I was simply using a local rsyslog (with the udp listener enabled) on my linux box.

**Comment by itsecureadmin** [comment]
@jakub-bochenski - I would prefer the protocol field or dropdown over the prefix and agree that its needed here for conformity.

On the tests, I'd prefer to remove the actual call to syslog and leave the mock as the UDP test has been basically a noop to date and all of the other tests do not send a message to a real service.

I will work on this.

**Comment by jakub-bochenski** [comment]
@itsecureadmin agree on both points

**Comment by itsecureadmin** [comment]
@jakub-bochenski - I recently discovered PR 22 which obsoletes the work that I'm doing here for a specific project.  If there is not a compelling reason to continue this work, I'd prefer to abort and focus efforts elsewhere.

**Pull request closed without merging**
