### PR TITLE
Syslog persistence integration test with docker and travis.

### PR DESCRIPTION
**Pull request by sysadmin4j**
Following this pull request https://github.com/jenkinsci/logstash-plugin/pull/26, I decided to improve the syslogSend() test.

I tried to embedded a java syslog server but I figured it wouldn't be a real test since the final destination of the messages need to be logstash. Logstash is not written in java, so I didn't found an easy way to embedded it. 

The solution I propose rely on the logstash docker image which is started by travis before the build start. The logstash version can be easily updated via the .travis config file.The started logstash docker image could be reused for other persistence integration tests like Redis and RabbitMQ. 

In this pull request I also updated the Syslog format to be compliant with the logstash syslog input plugin.

I hope it can help!

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Thanks @sysadmin4j 

> In this pull request I also updated the Syslog format to be compliant with the logstash syslog input plugin.
I wouldn't want to break things for people who might just be using this to send messages in RFC5424. Can we either make this into a new indexer type (`SYSLOG_RFC3164` or `LOGSTASH_SYSLOG`) or add a new field to choose the format?

**Comment by jakub-bochenski** [comment]
I see the tests are failing on Jenkins, probably because it's not setting up said docker image.

I have some suggestions here:
 - it was a bit hard to read the failure message -- can you change the test to fail with a more user friendly message if the file is empty?
 - I think we should mark this case as an integration test instead -- this implies moving it from surefire to failsafe plugin 
 - if w do above we could skip the integration tests on Jenkins, since I don't think it lets you setup docker images for the build (?)
 - to keep project structure clean can we move the `src/test/resources/logs/` somewhere under `target`?

**Comment by sysadmin4j** [comment]
@jakub-bochenski, thanks for the review.

> I wouldn't want to break things for people who might just be using this to send messages in RFC5424. Can we either make this into a new indexer type (SYSLOG_RFC3164 or LOGSTASH_SYSLOG) or add a new field to choose the format?

What do you think about using the existing configuration field named **key** to specify the format ?
(If the field is left blank I would use _RFC5424_)

I can also try to modify the jelly configuration form to add a conditional field named **format** if the **Indexer type** selected is _SYSLOG_.

Let me know what you prefer!

> I see the tests are failing on Jenkins, probably because it's not setting up said docker image.

Yes, I realized after submitting the PR that there was a Jenkins build.

I will follow all your suggestions and make the integration test run only on Travis with the failsafe maven plugin.

**Comment by jakub-bochenski** [comment]
@sysadmin4j I'd prefer a new drop-down, since using the `key` field would be a stretch.

Actually I think it might be useful to map `key` to syslog's `indent` - WDYT?

**Comment by sysadmin4j** [comment]
> Actually I think it might be useful to map key to syslog's indent - WDYT?

Yes I agree, it make sens to map the key to syslog's ident (program name).

**Comment by jakub-bochenski** [comment]
@sysadmin4j bump; I'm still waiting for the drop-down mentioned in https://github.com/jenkinsci/logstash-plugin/pull/27#issuecomment-307291805

**Comment by sysadmin4j** [comment]
@jakub-bochenski, I have been struggling for that one. It's not exactly like I mentioned in the previous comment, instead I placed the dropdown menu under the advanced setting section. I can try to use something like this https://github.com/jenkinsci/ui-samples-plugin/blob/master/src/main/resources/jenkins/plugins/ui_samples/DropdownList/index.jelly but I am not sure if it would be the right way to do it. Do you have any suggestions ?

**Comment by jakub-bochenski** [comment]
@sysadmin4j sadly I don't know much about Jenkins Jelly :(
I think for now it's fine to add a static field (named "Syslog format"?) with some explanation in help. 

IMO the settings form needs a major overhaul sometimes later anyhow.

**Comment by sysadmin4j** [comment]
> I think for now it's fine to add a static field (named "Syslog format"?) with some explanation in help.

Alright @jakub-bochenski , I will keep the field static and add some explanation for it in the help .

> IMO the settings form needs a major overhaul sometimes later anyhow.

I guess you would rebuild it using groovy instead of jelly?

On another topic, I was thinking about replacing the: `Thread.sleep(2000);` for [awaitility](https://github.com/awaitility/awaitility/) in the SyslogDao integration test. WDYT?

**Comment by jakub-bochenski** [comment]
> I guess you would rebuild it using groovy instead of jelly?
One can easily see it needs an overhaul, I haven't thought about how to go about it though. 
Suggestions are welcome, but currently I like jelly more for the reasons outlined here: https://groups.google.com/d/msg/jenkinsci-dev/n4Xw9pq2fl8/-EHShBSBAQAJ

> On another topic, I was thinking about replacing the: Thread.sleep(2000); for awaitility in the SyslogDao integration test. WDYT?
+1 I've been using awaitility in other projects with good results

**Comment by jakub-bochenski** [comment]
Looks good overall but the build failed on Travis -- can you check?

Please rebase the MR against master to re-enable Jenkins builds

**Comment by sysadmin4j** [comment]
> Looks good overall but the build failed on Travis -- can you check?

I can see two problems that seems to be caused by the [latest Travis updates](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch):

1) Docker or the OS (Ubuntu Trusty) don't accept UDP packets anymore.

https://github.com/moby/moby/issues/8795

I am still investigating this one. 

2) Openjdk7 support broken

https://github.com/travis-ci/travis-ci/issues/7964
 
A quick workaround for both problems would be to add  `group: deprecated-2017Q2` in the travis configuration. Note: This workaround will work only until 01-09-2017.

**Comment by sysadmin4j** [comment]
> Docker or the OS (Ubuntu Trusty) don't accept UDP packets anymore.

Finally it was not related to UDP at all, it was a system permission issue. The travis UID has changed from 1000 to 2000 with an [update](https://github.com/travis-ci/travis-ci/issues/7995).

> Oraclejdk7 support broken

Since [Oraclejdk7 is no longer supported by travis](https://github.com/travis-ci/travis-ci/issues/7964#issuecomment-316769421), may I suggest removing it and adding Openjdk8 instead. @jakub-bochenski , I will be waiting for your feedback.

**Comment by jakub-bochenski** [comment]
> Since Oraclejdk7 is no longer supported by travis, may I suggest removing it and adding Openjdk8 instead. 
Agreed, will merge #34 once the checks pass

**Pull request merged**
