### PR TITLE
support custom log lines processing via script 

### PR DESCRIPTION
**Pull request by jakub-bochenski**
Second attempt at #40 

> This change requires jenkinsci/script-security-plugin#169 to work.
> 
> Please see `help-script.html` for possible use cases.
> 
> I needed to update parent pom version because of script-security-plugin which led to
> the need to suppress additional warnings. Still waiting on
> jenkinsci/script-security-plugin#169 to be accepted so not ready to merge. I have an
> alternative approach if the pull is not accepted, unfortunately not that performant.
> 
> But I will appreciate feedback for this PR in the meanwhile so I can fix issues.

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
@jglick I would certainly be interested in both having script processing and using the slaves to push the logs instead of master (mostly because our main Jenkins master is a 20GB ram hog).

Would it be possible to do script processing on slaves?

As for the use cases (and not to anwser for @akostadinov ) for me the biggest use case is actually not about processing the message itself, but about the metadata sent along with it.
The json payload is bloated with a lot of attributes e.g. "rootFullProjectName", "fullDisplayName", "rootProjectName", "fullProjectName" and "projectName" because people keep adding more to fit their needs. I hope we could remove most (if not all of it) by default and just let people add metadata they want via script.

Other people also seem to be interested in this metadata processing, e.g. https://issues.jenkins-ci.org/browse/JENKINS-50455

**Comment by jakub-bochenski** [comment]
@akostadinov so how are things going? Do you think you will manage to look into this PR any time soon?

**Comment by akostadinov** [comment]
I hope so, but since we got a new release under testing, There are so far constantly other "urgent" tasks.

**Comment by akostadinov** [comment]
Finally got back to this. Seems like a lot of new conflicts. Tough luck ¯\_(ツ)_/¯

**Comment by akostadinov** [comment]
This one should be closed as I can't update it. I opened #71 to track it.

**Pull request closed without merging**
