### PR TITLE
[JENKINS-34891] Fixed dependency to mask-passwords

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by R-Gerard** [comment]
I haven't had time to investigate the problem. Simply marking the mask-passwords plugin as required is the easy fix, but correctly ensuring that it is optional would be preferable. I know that @Spitfire1900 was able to run the logstash plugin without the mask-passwords plugin installed. Maybe he can provide some insight.

**Comment by Spitfire1900** [comment]
We currently use it without mask passwords installed, we are using commit 7b20502 at the moment.

**Comment by akostadinov** [comment]
Do we still need mask passwords to be optional?

**Comment by mwinter69** [comment]
obsolete since #48 made mask passwords not needed anymore

**Pull request closed without merging**
