### PR TITLE
File formatting improvements

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Thanks, but I would rather format this according to goolge style guide and add a formatting plugin (e.g. fmt-maven-plugin) to keep the files formatted.
WDYT?

**Comment by darxriggs** [comment]
The performed changes are based on https://pre-commit.com/. They are basic and also covering non-Java files. You could use this tool for automated checks and/or a Java formatter which would be more involved.

**Comment by jakub-bochenski** [comment]
@darxriggs I took a look at the site you linked, but I don't see how would I make it work for a cloud github repo like this one.
I can't just login to Github server and `pip install` pre-commit there.

**Comment by jakub-bochenski** [comment]
.. or maybe I just got it wrong. 
If those are only client-side hooks they don't seem to be useful here. I don't want to have to manually run checks on every PR or rely on contributors to remember to run them. 
AFAIK there is no way to automate client-side hooks in Git for security reasons

**Comment by darxriggs** [comment]
The main purpose of these hooks is for local use. Fortunately the pre-commit framework can also be used on CI systems - see https://pre-commit.com/#usage-in-continuous-integration.

**Comment by jakub-bochenski** [comment]
@darxriggs I tried to add pre-commit to the Jenkinsfile. Right now it fails on git, even tough git is available.
Any idea how to make it work with the Jenkins plugin build infra?
```
[2019-08-07T15:01:00.835Z] + git --version
[2019-08-07T15:01:00.836Z] git version 2.17.1
...
[2019-08-07T15:01:04.961Z] + /home/jenkins/bin/pre-commit run --all-files
[2019-08-07T15:01:04.961Z] An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

**Comment by darxriggs** [comment]
I left you a comment - see [here](https://github.com/jenkinsci/logstash-plugin/pull/89/files#r311693642).

**Pull request merged**
