### PR TITLE
 Enable automatic release

### PR DESCRIPTION
**Pull request by jakub-bochenski**

### CODE REVIEW

**Comment by basil** [comment]
Hey @jakub-bochenski, thanks for working on the release of this plugin. Would it be possible to trigger a new release that contains #101? This would help the Jenkins core developers with the upcoming Guava upgrade.

**Comment by jakub-bochenski** [comment]
Hey @basil ,  I've tried to do that but the release process fails https://groups.google.com/g/jenkinsci-dev/c/wFpxyGF9IvA

**Comment by timja** [comment]
I would remove the incrementals config and re incrementalify the plugin it’s using an older version

**Comment by basil** [comment]
@jakub-bochenski Is there anything Tim or I could do to help? As Tim wrote above, re-incrementalifying this plugin should fix your problem. See https://github.com/jenkinsci/incrementals-tools and https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc for context.

**Comment by jakub-bochenski** [comment]
@basil sorry, it's just that my time for this is very limited recently

I will try to fix it tomorrow

**Comment by jakub-bochenski** [comment]
@basil  sorry for the delay
I have reincrementalified the plugin, but I still can't get the release out 
I'm trying to run the workflow manually, but the "release" part just has "check skipped" 
e.g. https://github.com/jenkinsci/logstash-plugin/actions/runs/1258235986

**Comment by timja** [comment]
https://www.jenkins.io/jep/229 relies on the master build to have completed on ci.jenkins.io, it's currently running here: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flogstash-plugin/detail/master/75/pipeline

Also you'll want to label the PRs as they come in according to the release drafter config: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml

e.g. `enhancement` possibly for https://github.com/jenkinsci/logstash-plugin/pull/102

By default it will only release what it considers interesting categories: https://github.com/jenkins-infra/interesting-category-action/blob/main/action.yaml#L13.

Although when you trigger a release yourself with the `workflow_dispatch` trigger on the actions page the interesting categories will be ignored

**Comment by jakub-bochenski** [comment]
Thanks

@timja  so if I want to force a release I need to wait for https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flogstash-plugin/detail/master/75/pipeline to complete, then run the workflow manually again?

**Comment by timja** [comment]
> Thanks
> 
> @timja so if I want to force a release I need to wait for [ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flogstash-plugin/detail/master/75/pipeline](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flogstash-plugin/detail/master/75/pipeline) to complete, then run the workflow manually again?

yes, and it's finished now, so try trigger it

**Comment by jakub-bochenski** [comment]
OK, it seems the release is running now

Big thanks for all the help!

**Comment by timja** [comment]
It's out, nice wall of text in https://github.com/jenkinsci/logstash-plugin/releases/tag/2.5.0205.vd05825ed46bd

you might want to do a review and make sure all of that was actually in the release as the first release may show older content, going forward it'll be fine

**Comment by basil** [comment]
Is that version number correct? "2.5.0205.vd05825ed46bd" looks odd to me... shouldn't that be "205.vd05825ed46bd"?

**Comment by jakub-bochenski** [comment]
@basil give that the previous version was 2.4.0 then 2.5 looks fine to me

**Comment by basil** [comment]
But "0205" makes no sense as a number. Anyway, don't mind me, I am not much of a fan of JEP-229 anyway. Thanks for releasing this.

**Comment by basil** [comment]
This probably isn't the best forum to have this discussion, but I think this user's experience illustrates some of the challenges. The user tried their best and still ended up with an incorrect `<version>${revision}${changelist}</version>` in their `pom.xml` and a nonsensical `2.5.0205.vd05825ed46bd` release number. The whole process seems to lack polish, not to mention my subjective dislike of the large numbers and the use of GitHub Actions (which would be way out of scope of this PR's comment section to explain).

**Comment by basil** [comment]
@jakub-bochenski The point is that JEP-229 is designed to be used with `<version>${changelist}</version>`, which does result in very large version numbers that many (including myself) find unappealing. You can certainly keep using `<version>${revision}${changelist}</version>` if you want, but it will result in some weirdness, like the "0205" number.

**Comment by jakub-bochenski** [comment]
@basil that wasn't intentional but I've just noticed I did this accidentally while re-incrementalifying.

If this will work then I think I'm happy keeping "low" major/minor version for the price of some weird numbers in patch

**Comment by basil** [comment]
I don't have a strong opinion one way or another; as I mentioned, I don't use JEP-229 in the plugins I maintain. Just pointing out the common convention for people who _are_ using JEP-229.

**Pull request merged**
